README.md

docs: re-enable goreport card

---

scripts/dockerbuild-dev.sh

build: add dockerbuild-dev.sh script

---

.codecov.yml

otherwise codecov global uploader may pick one from vendor dir [skip ci]

ci: add codecov yaml config

---

web/ui/src/app/views/base/tables.component.ts

fix: remove unnecessary window reload

---

docs/directive_and_alarm.md
internal/pkg/dsiem/siem/backlog.go

Previously risk is calculated upon *entering* a correlation stage. This moves it to the end of stage for better alignment with OSSIM behavior.

fix: calculate risk at the of stage

---

docs/dsiem_plugin.md

docs: update status on corr. based on custom_data

---

docs/building.md
scripts/gobuild-cmd.sh
scripts/ngbuild-web.sh

docs: add info on how to build from src

---

docs/installation.md

docs: update manual install procedure

---

cmd/dsiem/main.go

fix: print msg on successful directive validation

---

scripts/gobuild-cmd-release.sh

ci: release of linux ver. of the server binary

---

web/ui/src/app/views/base/tables.component.html

fix: unresponsive table

---

cmd/dsiem/main.go
internal/pkg/dsiem/event/event.go
internal/pkg/dsiem/queue/event_queue.go
internal/pkg/dsiem/queue/goconcurrentqueue/README.md
internal/pkg/dsiem/queue/goconcurrentqueue/error.go
internal/pkg/dsiem/queue/goconcurrentqueue/fifo_queue.go
internal/pkg/dsiem/queue/goconcurrentqueue/fixed_fifo_queue.go
internal/pkg/dsiem/queue/goconcurrentqueue/queue.go
internal/pkg/dsiem/siem/directive.go
internal/pkg/dsiem/siem/directive_test.go

feat: add option to set max queue length

---

internal/pkg/dsiem/vice/README.md

docs: add reference to vice source repo

---

scripts/gobuild-cmd-release.sh

the err caused by #208
[skip ci]

build: fix tools build err for win and darwin

---

internal/pkg/dsiem/worker/worker.go

error introduced in #176
[skip release]

fix: backpressure channel initialisation error

---

internal/pkg/dsiem/siem/backlogmgr.go

the faulty commit https://github.com/defenxor/dsiem/pull/230/commits/9c12db92f38b2387106983e070b8cc88fa1a9650 commented out a block that was meant to guard against this.

fix: regression error causing panic on a busy node

---

web/ui/src/app/views/base/tables.component.ts
web/ui/src/assets/config/esconfig.json

fix: unhandled exception when parse es url

---

.gitignore
demo/frontend/Dockerfile
demo/vagrant/alpine/Vagrantfile
demo/vagrant/ubuntu/Vagrantfile

build: add ignored Dockerfile and Vagrantfiles

---

demo/run.sh

build: apply demo host to kibana scripted field

---

deployments/docker/conf/logstash/scripts/allow_within_timerange.rb

chore: add LS ruby script to filter based on time

---

deployments/docker/conf/logstash/scripts/allow_within_timerange.rb

chore: fix typo in LS ruby script

---

demo/scripts/dpluger-reset.sh

chore: wrong directive file path in demo script

---

deployments/docker/conf/logstash/scripts/allow_within_timerange.rb

chore: typo in LS ruby script tests

---

docs/faq.md

docs: typo in FAQ

---

docs/faq.md

docs: add link to the docker image startup script

---

README.md

docs: add ref to demo section

---

web/ui/src/app/elasticsearch.service.ts

This will actually use defined basic auth configuration

fix: enable basic auth in web UI

---

docs/faq.md

docs: update ES CORS config in FAQ

---

web/ui/package-lock.json
web/ui/package.json

update acorn, websocket-extensions, npm-registry-fetch, lodash, elliptic, and http-proxy.

fix: web ui update dependencies

---

demo/frontend/web/package-lock.json

this will update elliptic, http-proxy, lodash, and websocket-extensions dependencies

fix: demo frontend web update deps

---

demo/run.sh

obtain suricata net interface in a more consistent way
[skipci]

chore: update demo script

---

demo/frontend/web/package-lock.json
demo/frontend/web/package.json

chore: update demo frontend deps

---

README.md

The PR is trivial and I don't think it needs any explanation but I'm always open to discussion.

Changed reference from Moloch to Arkime in README

---

internal/pkg/dsiem/rule/rule.go
internal/pkg/dsiem/rule/rule_test.go
internal/pkg/dsiem/siem/backlogmgr.go
internal/pkg/dsiem/siem/backlogmgr_test.go
internal/pkg/dsiem/siem/directive.go
internal/pkg/dsiem/siem/directive_test.go
internal/pkg/dsiem/siem/fixtures/directive5/directives_dsiem-backend-0_testing1.json
internal/pkg/dsiem/siem/validate.go
internal/pkg/dsiem/siem/validate_test.go

add:
- check on negative reference
- check on non-number reference
- check on non-exist reference
- check on reference on first rule stage
- handler to "ANY" in custom_data

feat: Improve directive validation

---

internal/pkg/nesd/server.go

- add sanitization for ip and port in `nesd` handler

Fix: add sanitization for ip and port

---

docs/dsiem_plugin.md
internal/pkg/dpluger/template.go

add documentation about embeding identifier block source from file

doc: update dsiem plugin documentation

---

internal/pkg/dpluger/dpluger.go
internal/pkg/dpluger/template.go

fix incorrect indentation for `dpluger run` with embedded identifier block

fix: fix incorrect indentation

---

internal/pkg/dpluger/dirmaker.go

* reliability value now uses value from parameter, with minimum and maximum limit guard.

fix: remove hardcoded reliability value

---

internal/pkg/dpluger/dirmaker.go

- add missing max value check for initial reliability value

fix: add maximum value for initial reliability

---

internal/pkg/dpluger/dirmaker.go
internal/pkg/dpluger/tsvref.go

fix: remove unnecessary steps on TSV parsing

---

internal/pkg/dpluger/dpluger.go
internal/pkg/dpluger/es5client.go
internal/pkg/dpluger/es6client.go
internal/pkg/dpluger/es7client.go
internal/pkg/dpluger/tsvref.go

fix issue where dpluger produce strange entry on plugin sid tsv file

fix: fix incorrect tsv initialization

---

internal/pkg/dpluger/es-info.go
internal/pkg/dpluger/esclient.go
internal/pkg/shared/logger/logger.go

* fix dpluger shows unsupported version on opensearch

Add support for opensearch

---

internal/pkg/dsiem/rule/rule.go
internal/pkg/dsiem/rule/rule_test.go

* fix incorrect rule matching for custom-data that contains space

fix dsiem directive rule custom data matching

---

demo/scripts/idxpattern-import.sh
demo/scripts/kbndashboard-import.sh

chore: remove extra string from 409 status
